language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base
  - cpan JSON
install:
  - ./configure
script:
  - ./git-rockstar ./

