#!/bin/bash

DIR=$( dirname $0 )
$DIR/configure > /dev/null
STATUS=$?
if [ "$STATUS" -ne 0 ]; then
    echo "Cannot run git-rockstar!"
    exit 1;
fi
source $DIR/.config 

GIT_REPO=$1
GIT_ROCKSTAR_CONFIG=$2
if [ -z "$GIT_REPO" ]; then
    echo "usage: $0 /path/to/my/git/repo [ /path/to/config/.git-rockstar ]"
    exit 1;
fi

OUT=$DIR/.git_rockstar_output
ERR=$DIR/.git_rockstar_error
echo '' > $OUT
echo '' > $ERR

$PERL $DIR/collect_git_stats.pl $GIT_REPO $GIT_ROCKSTAR_CONFIG 2> $ERR > $OUT
STATUS=$?
if [ "$STATUS" -ne 0 ]; then
    echo "Problems running collect_git_stats.pl!"
    cat $ERR
    exit 1;
fi

OUT2=$DIR/.git_rockstar_output2
ERR2=$DIR/.git_rockstar_error2
echo '' > $OUT2
echo '' > $ERR2

LABEL=""
GITHUB=$( cd $GIT_REPO; git config -l | /bin/grep github )
if [ -z "$GITHUB" ]; then
    # Not on github
    NAME=$( basename $GIT_REPO )
    LABEL="Code Changes for Git Repo [ $NAME ]"
else
    NAME=$( echo $GITHUB | sed -e 's|^.*github.com[/:]||;' )
    SHORT_NAME=$( echo $NAME | sed -e 's|.git$||;' )
    LABEL="Code Changes for Github [ $SHORT_NAME ]"
fi

echo $LABEL
exit 1;
$RSCRIPT $DIR/create_graph.R $OUT "'$LABEL'" 2> $ERR2 > $OUT2
STATUS=$?
if [ "$STATUS" -ne 0 ]; then
    echo "Problems running create_graph.R!"
    cat $DIR/.git_rockstar_error2
    exit 1;
fi

rm $OUT $OUT2 $ERR $ERR2
echo "Created PDF: $DIR/git_rockstar.pdf"
